/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeamChangeRequestsIndexRouteImport } from './routes/_authenticated/team-change-requests/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSeasonsIndexRouteImport } from './routes/_authenticated/seasons/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPlayersIndexRouteImport } from './routes/_authenticated/players/index'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches/index'
import { Route as AuthenticatedLeagueIndexRouteImport } from './routes/_authenticated/league/index'
import { Route as AuthenticatedDivisionsIndexRouteImport } from './routes/_authenticated/divisions/index'
import { Route as AuthenticatedDisputesIndexRouteImport } from './routes/_authenticated/disputes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedBugsIndexRouteImport } from './routes/_authenticated/bugs/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminLogsIndexRouteImport } from './routes/_authenticated/admin-logs/index'
import { Route as AuthenticatedUtilitiesSponsorsIndexRouteImport } from './routes/_authenticated/utilities/sponsors/index'
import { Route as AuthenticatedUtilitiesCategoriesIndexRouteImport } from './routes/_authenticated/utilities/categories/index'
import { Route as AuthenticatedSeasonsSeasonIdIndexRouteImport } from './routes/_authenticated/seasons/$seasonId/index'
import { Route as AuthenticatedPlayersPlayerIdIndexRouteImport } from './routes/_authenticated/players/$playerId/index'
import { Route as AuthenticatedLeagueLeagueIdIndexRouteImport } from './routes/_authenticated/league/$leagueId/index'
import { Route as AuthenticatedDivisionsDivisionIdIndexRouteImport } from './routes/_authenticated/divisions/$divisionId/index'
import { Route as AuthenticatedAdminAdminIdIndexRouteImport } from './routes/_authenticated/admin/$adminId/index'
import { Route as AuthenticatedLeagueViewLeagueIdIndexRouteImport } from './routes/_authenticated/league/view/$leagueId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamChangeRequestsIndexRoute =
  AuthenticatedTeamChangeRequestsIndexRouteImport.update({
    id: '/team-change-requests/',
    path: '/team-change-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeasonsIndexRoute =
  AuthenticatedSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersIndexRoute =
  AuthenticatedPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueIndexRoute =
  AuthenticatedLeagueIndexRouteImport.update({
    id: '/league/',
    path: '/league/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDivisionsIndexRoute =
  AuthenticatedDivisionsIndexRouteImport.update({
    id: '/divisions/',
    path: '/divisions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputesIndexRoute =
  AuthenticatedDisputesIndexRouteImport.update({
    id: '/disputes/',
    path: '/disputes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBugsIndexRoute = AuthenticatedBugsIndexRouteImport.update({
  id: '/bugs/',
  path: '/bugs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogsIndexRoute =
  AuthenticatedAdminLogsIndexRouteImport.update({
    id: '/admin-logs/',
    path: '/admin-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUtilitiesSponsorsIndexRoute =
  AuthenticatedUtilitiesSponsorsIndexRouteImport.update({
    id: '/utilities/sponsors/',
    path: '/utilities/sponsors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUtilitiesCategoriesIndexRoute =
  AuthenticatedUtilitiesCategoriesIndexRouteImport.update({
    id: '/utilities/categories/',
    path: '/utilities/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeasonsSeasonIdIndexRoute =
  AuthenticatedSeasonsSeasonIdIndexRouteImport.update({
    id: '/seasons/$seasonId/',
    path: '/seasons/$seasonId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPlayerIdIndexRoute =
  AuthenticatedPlayersPlayerIdIndexRouteImport.update({
    id: '/players/$playerId/',
    path: '/players/$playerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueLeagueIdIndexRoute =
  AuthenticatedLeagueLeagueIdIndexRouteImport.update({
    id: '/league/$leagueId/',
    path: '/league/$leagueId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDivisionsDivisionIdIndexRoute =
  AuthenticatedDivisionsDivisionIdIndexRouteImport.update({
    id: '/divisions/$divisionId/',
    path: '/divisions/$divisionId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminIdIndexRoute =
  AuthenticatedAdminAdminIdIndexRouteImport.update({
    id: '/admin/$adminId/',
    path: '/admin/$adminId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeagueViewLeagueIdIndexRoute =
  AuthenticatedLeagueViewLeagueIdIndexRouteImport.update({
    id: '/league/view/$leagueId/',
    path: '/league/view/$leagueId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-logs': typeof AuthenticatedAdminLogsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bugs': typeof AuthenticatedBugsIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/disputes': typeof AuthenticatedDisputesIndexRoute
  '/divisions': typeof AuthenticatedDivisionsIndexRoute
  '/league': typeof AuthenticatedLeagueIndexRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/seasons': typeof AuthenticatedSeasonsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/team-change-requests': typeof AuthenticatedTeamChangeRequestsIndexRoute
  '/admin/$adminId': typeof AuthenticatedAdminAdminIdIndexRoute
  '/divisions/$divisionId': typeof AuthenticatedDivisionsDivisionIdIndexRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdIndexRoute
  '/seasons/$seasonId': typeof AuthenticatedSeasonsSeasonIdIndexRoute
  '/utilities/categories': typeof AuthenticatedUtilitiesCategoriesIndexRoute
  '/utilities/sponsors': typeof AuthenticatedUtilitiesSponsorsIndexRoute
  '/league/view/$leagueId': typeof AuthenticatedLeagueViewLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-logs': typeof AuthenticatedAdminLogsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bugs': typeof AuthenticatedBugsIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/disputes': typeof AuthenticatedDisputesIndexRoute
  '/divisions': typeof AuthenticatedDivisionsIndexRoute
  '/league': typeof AuthenticatedLeagueIndexRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/players': typeof AuthenticatedPlayersIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/seasons': typeof AuthenticatedSeasonsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/team-change-requests': typeof AuthenticatedTeamChangeRequestsIndexRoute
  '/admin/$adminId': typeof AuthenticatedAdminAdminIdIndexRoute
  '/divisions/$divisionId': typeof AuthenticatedDivisionsDivisionIdIndexRoute
  '/league/$leagueId': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/players/$playerId': typeof AuthenticatedPlayersPlayerIdIndexRoute
  '/seasons/$seasonId': typeof AuthenticatedSeasonsSeasonIdIndexRoute
  '/utilities/categories': typeof AuthenticatedUtilitiesCategoriesIndexRoute
  '/utilities/sponsors': typeof AuthenticatedUtilitiesSponsorsIndexRoute
  '/league/view/$leagueId': typeof AuthenticatedLeagueViewLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin-logs/': typeof AuthenticatedAdminLogsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bugs/': typeof AuthenticatedBugsIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/disputes/': typeof AuthenticatedDisputesIndexRoute
  '/_authenticated/divisions/': typeof AuthenticatedDivisionsIndexRoute
  '/_authenticated/league/': typeof AuthenticatedLeagueIndexRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/players/': typeof AuthenticatedPlayersIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/seasons/': typeof AuthenticatedSeasonsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/team-change-requests/': typeof AuthenticatedTeamChangeRequestsIndexRoute
  '/_authenticated/admin/$adminId/': typeof AuthenticatedAdminAdminIdIndexRoute
  '/_authenticated/divisions/$divisionId/': typeof AuthenticatedDivisionsDivisionIdIndexRoute
  '/_authenticated/league/$leagueId/': typeof AuthenticatedLeagueLeagueIdIndexRoute
  '/_authenticated/players/$playerId/': typeof AuthenticatedPlayersPlayerIdIndexRoute
  '/_authenticated/seasons/$seasonId/': typeof AuthenticatedSeasonsSeasonIdIndexRoute
  '/_authenticated/utilities/categories/': typeof AuthenticatedUtilitiesCategoriesIndexRoute
  '/_authenticated/utilities/sponsors/': typeof AuthenticatedUtilitiesSponsorsIndexRoute
  '/_authenticated/league/view/$leagueId/': typeof AuthenticatedLeagueViewLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-logs'
    | '/admin'
    | '/bugs'
    | '/chat'
    | '/dashboard'
    | '/disputes'
    | '/divisions'
    | '/league'
    | '/matches'
    | '/players'
    | '/reports'
    | '/seasons'
    | '/settings'
    | '/team-change-requests'
    | '/admin/$adminId'
    | '/divisions/$divisionId'
    | '/league/$leagueId'
    | '/players/$playerId'
    | '/seasons/$seasonId'
    | '/utilities/categories'
    | '/utilities/sponsors'
    | '/league/view/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-logs'
    | '/admin'
    | '/bugs'
    | '/chat'
    | '/dashboard'
    | '/disputes'
    | '/divisions'
    | '/league'
    | '/matches'
    | '/players'
    | '/reports'
    | '/seasons'
    | '/settings'
    | '/team-change-requests'
    | '/admin/$adminId'
    | '/divisions/$divisionId'
    | '/league/$leagueId'
    | '/players/$playerId'
    | '/seasons/$seasonId'
    | '/utilities/categories'
    | '/utilities/sponsors'
    | '/league/view/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin-logs/'
    | '/_authenticated/admin/'
    | '/_authenticated/bugs/'
    | '/_authenticated/chat/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/disputes/'
    | '/_authenticated/divisions/'
    | '/_authenticated/league/'
    | '/_authenticated/matches/'
    | '/_authenticated/players/'
    | '/_authenticated/reports/'
    | '/_authenticated/seasons/'
    | '/_authenticated/settings/'
    | '/_authenticated/team-change-requests/'
    | '/_authenticated/admin/$adminId/'
    | '/_authenticated/divisions/$divisionId/'
    | '/_authenticated/league/$leagueId/'
    | '/_authenticated/players/$playerId/'
    | '/_authenticated/seasons/$seasonId/'
    | '/_authenticated/utilities/categories/'
    | '/_authenticated/utilities/sponsors/'
    | '/_authenticated/league/view/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team-change-requests/': {
      id: '/_authenticated/team-change-requests/'
      path: '/team-change-requests'
      fullPath: '/team-change-requests'
      preLoaderRoute: typeof AuthenticatedTeamChangeRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons/': {
      id: '/_authenticated/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof AuthenticatedSeasonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/': {
      id: '/_authenticated/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/': {
      id: '/_authenticated/league/'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof AuthenticatedLeagueIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/divisions/': {
      id: '/_authenticated/divisions/'
      path: '/divisions'
      fullPath: '/divisions'
      preLoaderRoute: typeof AuthenticatedDivisionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes/': {
      id: '/_authenticated/disputes/'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bugs/': {
      id: '/_authenticated/bugs/'
      path: '/bugs'
      fullPath: '/bugs'
      preLoaderRoute: typeof AuthenticatedBugsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-logs/': {
      id: '/_authenticated/admin-logs/'
      path: '/admin-logs'
      fullPath: '/admin-logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilities/sponsors/': {
      id: '/_authenticated/utilities/sponsors/'
      path: '/utilities/sponsors'
      fullPath: '/utilities/sponsors'
      preLoaderRoute: typeof AuthenticatedUtilitiesSponsorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/utilities/categories/': {
      id: '/_authenticated/utilities/categories/'
      path: '/utilities/categories'
      fullPath: '/utilities/categories'
      preLoaderRoute: typeof AuthenticatedUtilitiesCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seasons/$seasonId/': {
      id: '/_authenticated/seasons/$seasonId/'
      path: '/seasons/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof AuthenticatedSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$playerId/': {
      id: '/_authenticated/players/$playerId/'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof AuthenticatedPlayersPlayerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/$leagueId/': {
      id: '/_authenticated/league/$leagueId/'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueLeagueIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/divisions/$divisionId/': {
      id: '/_authenticated/divisions/$divisionId/'
      path: '/divisions/$divisionId'
      fullPath: '/divisions/$divisionId'
      preLoaderRoute: typeof AuthenticatedDivisionsDivisionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$adminId/': {
      id: '/_authenticated/admin/$adminId/'
      path: '/admin/$adminId'
      fullPath: '/admin/$adminId'
      preLoaderRoute: typeof AuthenticatedAdminAdminIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/league/view/$leagueId/': {
      id: '/_authenticated/league/view/$leagueId/'
      path: '/league/view/$leagueId'
      fullPath: '/league/view/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeagueViewLeagueIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminLogsIndexRoute: typeof AuthenticatedAdminLogsIndexRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBugsIndexRoute: typeof AuthenticatedBugsIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDisputesIndexRoute: typeof AuthenticatedDisputesIndexRoute
  AuthenticatedDivisionsIndexRoute: typeof AuthenticatedDivisionsIndexRoute
  AuthenticatedLeagueIndexRoute: typeof AuthenticatedLeagueIndexRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
  AuthenticatedPlayersIndexRoute: typeof AuthenticatedPlayersIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSeasonsIndexRoute: typeof AuthenticatedSeasonsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTeamChangeRequestsIndexRoute: typeof AuthenticatedTeamChangeRequestsIndexRoute
  AuthenticatedAdminAdminIdIndexRoute: typeof AuthenticatedAdminAdminIdIndexRoute
  AuthenticatedDivisionsDivisionIdIndexRoute: typeof AuthenticatedDivisionsDivisionIdIndexRoute
  AuthenticatedLeagueLeagueIdIndexRoute: typeof AuthenticatedLeagueLeagueIdIndexRoute
  AuthenticatedPlayersPlayerIdIndexRoute: typeof AuthenticatedPlayersPlayerIdIndexRoute
  AuthenticatedSeasonsSeasonIdIndexRoute: typeof AuthenticatedSeasonsSeasonIdIndexRoute
  AuthenticatedUtilitiesCategoriesIndexRoute: typeof AuthenticatedUtilitiesCategoriesIndexRoute
  AuthenticatedUtilitiesSponsorsIndexRoute: typeof AuthenticatedUtilitiesSponsorsIndexRoute
  AuthenticatedLeagueViewLeagueIdIndexRoute: typeof AuthenticatedLeagueViewLeagueIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminLogsIndexRoute: AuthenticatedAdminLogsIndexRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBugsIndexRoute: AuthenticatedBugsIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDisputesIndexRoute: AuthenticatedDisputesIndexRoute,
  AuthenticatedDivisionsIndexRoute: AuthenticatedDivisionsIndexRoute,
  AuthenticatedLeagueIndexRoute: AuthenticatedLeagueIndexRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
  AuthenticatedPlayersIndexRoute: AuthenticatedPlayersIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSeasonsIndexRoute: AuthenticatedSeasonsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTeamChangeRequestsIndexRoute:
    AuthenticatedTeamChangeRequestsIndexRoute,
  AuthenticatedAdminAdminIdIndexRoute: AuthenticatedAdminAdminIdIndexRoute,
  AuthenticatedDivisionsDivisionIdIndexRoute:
    AuthenticatedDivisionsDivisionIdIndexRoute,
  AuthenticatedLeagueLeagueIdIndexRoute: AuthenticatedLeagueLeagueIdIndexRoute,
  AuthenticatedPlayersPlayerIdIndexRoute:
    AuthenticatedPlayersPlayerIdIndexRoute,
  AuthenticatedSeasonsSeasonIdIndexRoute:
    AuthenticatedSeasonsSeasonIdIndexRoute,
  AuthenticatedUtilitiesCategoriesIndexRoute:
    AuthenticatedUtilitiesCategoriesIndexRoute,
  AuthenticatedUtilitiesSponsorsIndexRoute:
    AuthenticatedUtilitiesSponsorsIndexRoute,
  AuthenticatedLeagueViewLeagueIdIndexRoute:
    AuthenticatedLeagueViewLeagueIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
